#!/usr/bin/env bash
# DevOps 0x0C. Web server - task 0. Transfer a file to your server
# transfers file to user home directory in remote server
if (( $# < 3 || $# > 4 )); then
    echo 'Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY'
elif (( $# == 4 )); then
    scp -i "$4" -o StrictHostKeyChecking=no "$1" "$3@$2:~/"
else
    scp -o StrictHostKeyChecking=no "$1" "$3@$2:~/"
fi
