#!/usr/bin/env bash
# installs nginx web server, listening on port 80; dummy index page
apt-get -y update
apt-get -y install nginx
echo "Holberton School" > /var/www/html/index.html
service nginx restart
