#!/usr/bin/env bash
# setup nginx web server, including 301 redirect
sudo apt-get -y update
sudo apt-get -y install nginx

sudo bash -c 'echo "Holberton School" > /var/www/html/index.html'

sudo sed "listen [::]:80 default_server;/a\	rewrite ^/redirect_me https://www.youtube.com/watch?v=mTEros927Ow permanent;" /etc/nginx/sites-available/default

sudo service nginx start
