#!/usr/bin/env bash
# setup nginx web server, including 301 redirect
apt-get -y update
apt-get -y install nginx

echo "Holberton School" > /var/www/html/index.html

sed -i "/listen \[::]:80 default_server;/a\	rewrite ^/redirect_me/?.*$ https://www.youtube.com/watch?v=mTEros927Ow permanent;" /etc/nginx/sites-available/default

service nginx start
