#!/usr/bin/env bash
# 0x0F. Load balancer - 0. Double the number of webservers
# setup nginx web server, including 301 redirect, 404, and HTTP response header
apt-get -y update
apt-get -y install nginx

echo 'Holberton School' > /var/www/html/index.html
echo "Ceci n'est pas une page" > /var/www/html/404.html

sed -i "/listen \[::]:80 default_server;/a\	rewrite ^/redirect_me/?.*$ https://www.youtube.com/watch?v=mTEros927Ow permanent;" /etc/nginx/sites-available/default
sed -i "/listen \[::]:80 default_server;/a\	error_page 404 /404.html;" /etc/nginx/sites-available/default
sed -i '/http {/a\\n\tadd_header X-Served-By '"${HOSTNAME}"';' /etc/nginx/nginx.conf

service nginx restart
