#!/usr/bin/env bash
# container-specific fix to restore nginx service listening (only) on port 80
ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
NGINX_PID=$(pgrep -u root nginx)
echo "$NGINX_PID" > /run/nginx.pid
service nginx reload
