#!/usr/bin/env bash
# restore nginx service listening on port 80, but invisible to `service`
ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx restart
rm /run/nginx.pid
