#!/usr/bin/env bash
# This script is displaying "Holberton School" 10 times, and "Hi" after 9th
i=0
while (( i < 10 )); do
echo 'Holberton School';
if ((i == 8)); then echo 'Hi'; fi
((i++)); done
unset i
