#!/usr/bin/env bash
# This script is displaying "Holberton School" 10 times, substituting
# messages at the 4th and 8th lines
i=0; while (( i < 10 )); do
if (( i == 3 )); then echo 'bad luck'
elif (( i == 7 )); then echo 'good luck'
else echo 'Holberton School'; fi
((i++)); done
unset i
