#!/usr/bin/env bash
# This script displays hour and minute updates from 00:00 to 12:59
i=0; while (( i < 13 )); do
echo 'Hour:' $i
j=1; while (( j < 60 )); do
echo $j; ((j++)); done
((i++)); done
unset i; unset j
