#!/usr/bin/env bash
# more sustainable way to get nginx running as user `nginx`
apache_pid="$(pgrep apache2 | head -n 1)"
echo "$apache_pid" > /run/apache2/apache2.pid
service apache2 stop
sed -i "s/80 default_serv/8080 default_serv/" /etc/nginx/sites-available/default
sed -i '/user www-data;$/a user nginx;' /etc/nginx/nginx.conf
chown nginx:nginx /etc/nginx/nginx.conf
chmod 644 /etc/nginx/nginx.conf
sudo -u nginx service nginx restart
